# SPDX-License-Identifier: MIT
name: CI

on:
  push:

env:
  IMAGE_VERSION: "5.5.5"
  IMAGE: "mock-op"

jobs:

  local-build:
    name: Local build
    strategy:
      matrix:
        os: [ubuntu-18.04]
        go: [1.14]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare
      run: go mod download
    - name: Build
      run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o build/bin/namespace-provisioner -mod=readonly -v
    - name: Test
      run: |
        mkdir -p build/coverage-results
        mkdir -p build/test-results
        TEST_RESULT_DIR=../../build/test-results go test -mod=readonly -coverprofile=build/coverage-results/coverage.out -covermode count -v ./...
        go tool cover -html build/coverage-results/coverage.out -o build/coverage-results/coverage.html
